version: '2'

services:
    web:
        build: web
        volumes:
            - ./data/www:/var/www/html/
            - ./data/archives:/root/drush-backups
        ports:
            - "80:80"
        links:
            - mysql
        restart: always
    mysql:
        build: mysql
        environment:
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_DATABASE: "drupal8"
            MYSQL_ALLOW_EMPTY_PASSWORD: "no"
        ports:
            - "3306:3306"
        restart: always
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        environment:
            PMA_ARBITRARY: 0
            PMA_HOST: "mysql"
            PMA_PORT: 3306
            PMA_USER: "root"
            PMA_PASSWORD: "root"
        restart: always
        ports:
            - "8080:80"
        links:
            - mysql
        volumes:
            - /sessions
